description = "現在の開発ブランチの変更をステージング、コミット、プッシュし、アップストリーム追跡を設定します。"
prompt = """
現在の開発ブランチの変更をリモートリポジトリにプッシュし、アップストリーム追跡を設定します。

以下の手順を実行してください:

1.  **変更のステージング**:
    - `git add .` を実行して、すべての変更をステージングします。

2.  **変更のコミット**:
    - 現在のブランチ名を取得します（例: `develop/v0.2.2`）。
    - ブランチ名からイシュー番号を抽出します（例: `v0.2.2`）。
    - 以下の形式でコミットメッセージを生成します: `feat(issue_<イシュー番号>): Complete development for issue <イシュー番号>`
        - 例: `feat(issue_v0.2.2): Complete development for issue v0.2.2`
    - 生成したコミットメッセージで `git commit -m "<生成したコミットメッセージ>"` を実行して変更をコミットします。

3.  **ブランチのプッシュとアップストリーム追跡の設定**:
    - 現在のブランチ名を取得します。
    - `git push -u origin <現在のブランチ名>` を実行します。

これらの手順を完了したら、ユーザーに通知してください。
"""