description = "Git操作：コミット、タグ付け、mainへのマージ、新規ブランチ作成（例: /git v0.5.1）"
prompt = """
今回の変更をすべてステージングし、コミットし、バージョンを{{args}}としてタグ付けし、
現在のブランチをリモートにプッシュしてmainブランチにマージし、mainブランチをリモートにプッシュし、
新しい開発ブランチを作成してください。
最後に、古いブランチをローカル・リモートともに削除してください。

変更内容については、`docs/Issue/{{args}}.md`を参照し、コミットメッセージのタイトルと本文については、まず案を作成し、`.tmp/commit_message_<バージョン>.txt` のような一時ファイルに書き込んでからコミットします。
新しい開発ブランチ名も、まずは現在の開発ブランチ名から推測してユーザーに確認してください（v0.6.0なら次はv0.6.1です）。

.git/ディレクトリ以下のファイルに関して権限エラーが出た場合、そのファイルをを./tmpディレクトリに移動してみてください。
"""